name: Update Semver

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  update-semver:
    name: Update Semver
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: haya14busa/action-update-semver@v1
        with:
          major_version_tag_only: false
